### ISSUE TITLE
bug: eliminating any combinations of `$1` or `$2` from any environment variables on retrieve.

### ISSUE THREAD

**Issue by stevehebert** [subosito/gotenv#10]
Getting live environment variables that contain a $1 or $2 in a legitimate string is dropped from the variable

This combination can happen in a legitimate environment variable (like a password)

The line that causes the drop is here
https://github.com/subosito/gotenv/blob/27d387744383d355a04cdfada1736405440c595e/gotenv.go#L167

Trying to understand why this would be getting dropped in this way.

**Comment by luisdavim** [comment]
#16 should fix this as long as you use single quotes
