### ISSUE TITLE
multiline ENV variable?

### ISSUE THREAD

**Issue by sergolius** [subosito/gotenv#13]
Do you have any plans to support multiline ENV variables?
`linePattern` regex already supports it, but `bufio.NewScanner(r)` produces variable splitted by new line separator and makes it invalid before `linePattern` applied.

**Comment by lopezdonaque** [comment]
Any news?

**Comment by luisdavim** [comment]
I can look into this

**Comment by luisdavim** [comment]
I've opened #16 to address this.
