### ISSUE TITLE
Unclear specification in Usage instructions

### ISSUE THREAD

**Issue by Stektpotet** [subosito/gotenv#2]
I found the Usage section in instructions to be a bit unclear:
> Store your configuration to .env file on your root directory of your project

This may not always be the case. As many go projects are made up of multiple executables.
In my specific scenario:
I have a `rootdir` and the subsequent directories `rootdir/cmd/someWebService` and `rootdir/cmd/clock`, where clock is a simple ticker for the web-service.

As I've come to understand after messing around with gotenv for a while, what it actually does is reading files in directories relative to the file taking use of `gotenv.Load()`

Coming back to my scenario, I have to specify a relative path in `gotenv.Load(...)` for each of my executables. This is honestly not actually a bad thing, as it allows for more flexibility in my go code and file/folder structure. The point I'm trying to make is rather this:  The Usage instructions doesn't specify in a good manner where it reads from.

- Thank you

**Comment by subosito** [comment]
Thanks for your feedbacks @Stektpotet :+1:
