### ISSUE TITLE
StrictParse ignores scanner.Scan errors

### ISSUE THREAD

**Issue by arroyoh** [subosito/gotenv#23]
When reading the input buffer to parse the env, the returning method is ignoring any errors that might have occurred on the scanning process, if no line is read. We stumbled upon this while trying to read huge files that hit the scanner token limit, which was causing the scanner error  `ErrTooLong` to be returned, thus failing to read the buffer.

https://github.com/subosito/gotenv/blob/master/gotenv.go#L211

Should check for the scanner result with `scanner.Err()` method before returning [here](https://github.com/subosito/gotenv/blob/master/gotenv.go#L270)

**Comment by luisdavim** [comment]
Thanks for the PR #24
