### ISSUE TITLE
equal sign (=) character support

### ISSUE THREAD

**Issue by wiskarindra** [subosito/gotenv#4]
I'm trying to add a cert to .env file like this:
`CERT: "-----BEGIN CERTIFICATE-----\nMIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLh==........”`

but it doesn't works if there is equal sign _=_ character in the value

Any suggestion?

**Comment by subosito** [comment]
Using `\n` within quoted string makes it to be expanded as newline and `=` sign will be expanded to a new key-value env pair.

You can use `'` (single quote) to prevent such behaviour.

```
CERT: '-----BEGIN CERTIFICATE-----\nMIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLh==........'
```
