### ISSUE TITLE
Ignore missing files and options 

### ISSUE THREAD

**Issue by jooola** [subosito/gotenv#7]
I wanted to be able to ignore missing `.env` file, because I sometimes directly load environment variable without using the `.env` file (docker, or else ...).

So I wonder whether this package is open to add such options or if you want to keep it simple stupid ? Meaning that I will have to check if the files exists myself before loading.

Therefore I'd like to propose a extra LoadWithOptions function that allows on to define options such as `IgnoreMissingFiles`.

**Comment by luisdavim** [comment]
That's something you can handle on your code right?
